### ISSUE TITLE
Refactor grouped stops YAML structure

### ISSUE THREAD

**Issue by evanugarte** [SCE-Development/SCEta#35]
right now, we define a grouped stop like
```yaml
grouped_stops:
  - operator: CT
    group_name: San Jose Diridon Caltrain Station
    ids:
      - 70261
      - 70262
```

the above implies that the operator for a grouped stop must be the same for all ids. but what if we were dealing with a stop that had multiple operators (like VTA and Caltrain)?

lets refactor the grouped stops to be like below, where the below is identical to the above value
```yaml
grouped_stops:
  - name: San Jose Diridon Caltrain Station
    stops:
    - operator: CT
      id: 70261
    - operator: CT
      id: 70262
```

### game plan
- [ ] try to parse the above yaml values with the library we use https://pyyaml.org/wiki/PyYAMLDocumentation
- [ ] refactor the server to accept the new format for grouped stops, test locally with your own data.yaml

later we can refactor how we define fixed stops, as well as move the hardcoded stop id to coordinates mapping to its own file
